app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_logout:
        path:   /logout

#update_karma:
#    pattern:  /update/data/from/ajax/call
#    defaults: { _controller: AppBundle:User:updateKarma }
